import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {SidebarInset, SidebarProvider} from "@/components/ui/sidebar";
import {AppSidebar} from "@/components/app-sidebar";
import {ThemeProvider} from "@/components/theme-provider";
import {AppHeader} from "@/components/app-header";
import {TopLoader} from "@/components/top-loader";
import {QueryProvider} from "@/providers/query-provider";
import React from "react";
import {Toaster} from "sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "First Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <TopLoader/>
        <Toaster position={"top-right"}/>
        <ThemeProvider attribute={"class"} defaultTheme="system" enableSystem disableTransitionOnChange>
            <QueryProvider>
                <SidebarProvider>
                    <div className="flex h-screen w-screen overflow-hidden">
                        <AppSidebar />
                        <div className="flex flex-1 flex-col overflow-auto">
                            <AppHeader />
                            <main className="flex-1 p-2 overflow-auto">
                                {children}
                            </main>
                            <footer className="text-center p-2">
                                <p className="text-sm">&copy; 2025 Ecommerce App</p>
                            </footer>
                        </div>
                    </div>
                </SidebarProvider>
            </QueryProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
